language: php

php:
    - 5.6
    - 7
    - hhvm

env:
    - SYMFONY_VERSION=2.7.*

before_script:
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then pecl install crypto-0.1.1; fi;'
    - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
    - composer update --no-interaction

script:
    - vendor/bin/behat
