language: php

sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 7.0
    - php: 7.0
      env: deps=low
    - php: 7.1
    - php: 7.2
    - php: nightly

services:
    - memcached

before_script:
  # we remove xdebug support (not needed)
  - phpenv config-rm xdebug.ini || true

  # we add memcached extension
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # prepare composer and dependencies
  - composer self-update
  - if [[ $deps = low ]]; then composer update --no-interaction --prefer-lowest; fi
  - if [[ !$deps ]]; then composer install --no-interaction ; fi

script:
    - ./vendor/bin/behat
