language: php

php:
    - 5.6
    - 7.0
    - hhvm
    - nightly

matrix:
    allow_failures:
        - php: nightly

env:
    - SYMFONY_VERSION=2.7.*
    - SYMFONY_VERSION=2.8.*
    - SYMFONY_VERSION=3.0.*
    - SYMFONY_VERSION=3.1.*

before_script:
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi;'
    - composer self-update
    - composer require symfony/http-kernel:${SYMFONY_VERSION} --no-update
    - composer require symfony/dependency-injection:${SYMFONY_VERSION} --no-update
    - composer require symfony/config:${SYMFONY_VERSION} --no-update
    - composer update --no-interaction

script:
    - composer test
