language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7
    - hhvm

matrix:
    allow_failures:
        - php: 7
        - php: hhvm

env:
    - SYMFONY_VERSION=2.3.*
    - SYMFONY_VERSION=2.4.*
    - SYMFONY_VERSION=2.5.*
    - SYMFONY_VERSION=2.6.*
    - SYMFONY_VERSION=2.7.*@dev

before_script:
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then pecl install crypto-0.1.1; fi;'
    - curl -s http://getcomposer.org/installer | php
    - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
    - php composer.phar update --dev --no-interaction

script:
    - vendor/bin/behat
